# 1.2 - Numpy excercises [SOLVED]

In [11]:
import numpy as np

### Exercise: Removing negative numbers with *Fancy Indexing*

We have an array that has small negative numbers and we want to remove them, converting them to zero. First, we generate a random array.

In [12]:
np.random.seed(3)
a = np.random.random((5,4))-.2
a

array([[ 0.3507979 ,  0.50814782,  0.09090474,  0.31082761],
       [ 0.69294695,  0.69629309, -0.07441469,  0.00724288],
       [-0.1485328 ,  0.24080984, -0.17012379,  0.25683322],
       [ 0.44914405,  0.07848728,  0.4762549 ,  0.39086282],
       [-0.17601812,  0.35885409,  0.05925245,  0.2151012 ]])

In [13]:
a[(1,2,2,4),(2,2,0,0)] = 0
a

array([[ 0.3507979 ,  0.50814782,  0.09090474,  0.31082761],
       [ 0.69294695,  0.69629309,  0.        ,  0.00724288],
       [ 0.        ,  0.24080984,  0.        ,  0.25683322],
       [ 0.44914405,  0.07848728,  0.4762549 ,  0.39086282],
       [ 0.        ,  0.35885409,  0.05925245,  0.2151012 ]])

### Exercise: Removing negative numbers with *Boolean mask*

In [14]:
np.random.seed(3) #This way we can reproduce the same "random" array as before.
a = np.random.random((5,4))-.2
a

array([[ 0.3507979 ,  0.50814782,  0.09090474,  0.31082761],
       [ 0.69294695,  0.69629309, -0.07441469,  0.00724288],
       [-0.1485328 ,  0.24080984, -0.17012379,  0.25683322],
       [ 0.44914405,  0.07848728,  0.4762549 ,  0.39086282],
       [-0.17601812,  0.35885409,  0.05925245,  0.2151012 ]])

In [15]:
mask = [a<0]
a[mask]=0
a

array([[ 0.3507979 ,  0.50814782,  0.09090474,  0.31082761],
       [ 0.69294695,  0.69629309,  0.        ,  0.00724288],
       [ 0.        ,  0.24080984,  0.        ,  0.25683322],
       [ 0.44914405,  0.07848728,  0.4762549 ,  0.39086282],
       [ 0.        ,  0.35885409,  0.05925245,  0.2151012 ]])

Just to let you know, there's an alternative method for which the initial array a will not be modified

In [16]:
i = np.where(a<0,0,a)
i

array([[ 0.3507979 ,  0.50814782,  0.09090474,  0.31082761],
       [ 0.69294695,  0.69629309,  0.        ,  0.00724288],
       [ 0.        ,  0.24080984,  0.        ,  0.25683322],
       [ 0.44914405,  0.07848728,  0.4762549 ,  0.39086282],
       [ 0.        ,  0.35885409,  0.05925245,  0.2151012 ]])

# Homework
### Dot product

if __A__ is an _n × m_ matrix and __B__ is an _m × p_ matrix,

$ A_{n,m} = 
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,m} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,m} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{n,1} & a_{n,2} & \cdots & a_{n,m} 
 \end{pmatrix}
 $
 
 ##### $ B_{m,p} = 
 \begin{pmatrix}
  b_{1,1} & b_{1,2} & \cdots & b_{1,p} \\
  b_{2,1} & b_{2,2} & \cdots & b_{2,p} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  b_{m,1} & b_{m,2} & \cdots & b_{m,p} 
 \end{pmatrix}
 $
 
 The __matrix product AB__ (denoted without multiplication signs or dots) is defined to be the _n × p_ matrix
 
 ##### $ AB_{n,p} = 
 \begin{pmatrix}
  (ab)_{1,1} & (ab)_{1,2} & \cdots & (ab)_{1,p} \\
  (ab)_{2,1} & (ab)_{2,2} & \cdots & (ab)_{2,p} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  (ab)_{n,1} & (ab)_{n,2} & \cdots & (ab)_{n,p} 
 \end{pmatrix}
 $
 
 where each _i, j_ entry is given by multiplying the entries $A_{ik}$ (across row i of A) by the entries $B_{kj}$ (down column j of B), for k = 1, 2, ..., m, and summing the results over k:
 
$(AB)_{ij} = \displaystyle\sum_{k=1}^{m} A_{ik}B_{kj}$


### Exercise:
The dot product is so common that it is implemented in numpy. But if it was not there, could you code it?

In [3]:
A = np.random.randint(0,50,35).reshape(7,5)
B = np.random.randint(50,100,35).reshape(5,7)

In [4]:
[n,m] = A.shape

In [5]:
[m,p] = B.shape

In [6]:
AB = np.zeros((n,p))
AB

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
AB = np.zeros((n,p))

for i in range(n):
    for j in range(p):
        for k in range(m):
            AB[i,j] += A[i,k] * B[k,j]
AB

array([[  7260.,   4550.,   6228.,   5081.,   5123.,   5806.,   5795.],
       [ 11950.,   9302.,  11006.,  10785.,  11130.,  10778.,  10459.],
       [  9444.,   6284.,   8660.,   7957.,   7957.,   8124.,   8081.],
       [  8306.,   5986.,   7906.,   7201.,   7354.,   7266.,   7191.],
       [  9424.,   7624.,   9060.,   8068.,   8696.,   8888.,   8216.],
       [ 10253.,   8252.,   9774.,   9321.,   9780.,   9473.,   9054.],
       [ 13900.,  10960.,  12694.,  11232.,  12063.,  12666.,  11786.]])

In [8]:
%%timeit
for i in range(n):
    for j in range(p):
        for k in range(m):
            AB[i,j] += A[i,k] * B[k,j]

1000 loops, best of 3: 200 µs per loop


The following code with massive list comprehension uses a smart trick. 

__*Challenge*__ Can you recognise and understand it?

In [9]:
AB = [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]
AB

[[7260, 4550, 6228, 5081, 5123, 5806, 5795],
 [11950, 9302, 11006, 10785, 11130, 10778, 10459],
 [9444, 6284, 8660, 7957, 7957, 8124, 8081],
 [8306, 5986, 7906, 7201, 7354, 7266, 7191],
 [9424, 7624, 9060, 8068, 8696, 8888, 8216],
 [10253, 8252, 9774, 9321, 9780, 9473, 9054],
 [13900, 10960, 12694, 11232, 12063, 12666, 11786]]

In [10]:
%%timeit
AB = [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]

10000 loops, best of 3: 159 µs per loop


In [11]:
A.dot(B)

array([[ 7260,  4550,  6228,  5081,  5123,  5806,  5795],
       [11950,  9302, 11006, 10785, 11130, 10778, 10459],
       [ 9444,  6284,  8660,  7957,  7957,  8124,  8081],
       [ 8306,  5986,  7906,  7201,  7354,  7266,  7191],
       [ 9424,  7624,  9060,  8068,  8696,  8888,  8216],
       [10253,  8252,  9774,  9321,  9780,  9473,  9054],
       [13900, 10960, 12694, 11232, 12063, 12666, 11786]])

In [12]:
%%timeit
A.dot(B)

The slowest run took 25.97 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.19 µs per loop
